### ISSUE TITLE
jar file not getting load. 

### ISSUE THREAD

**Issue by aniketsonkamble07** [shoebham/text_to_isl#21]
allcsa.js:1219 07:00:44.254 Warn: 07:00:44.253 AGI   : Init: Failed to initialise
console.warn @ allcsa.js:1219Understand this warning
allcsa.js:1222 07:00:44.257 Log: 07:00:44.257 Log: [DEBUG] Setting SiGML URL: http://127.0.0.1:8000/SignFiles/B.sigml
allcsa.js:1222 07:00:44.399 Log: 07:00:44.399 Log: Config fetched successfully: Object
allcsa.js:1222 07:00:44.400 Log: 07:00:44.400 Log: Initializing CWASA with fetched config...
allcsa.js:1222 07:00:44.400 Log: 07:00:44.400 Log: CWASA initialized successfully.
allcsa.js:1222 07:00:44.400 Log: 07:00:44.400 Log: [DEBUG] Setting SiGML URL: http://127.0.0.1:8000/SignFiles/bad.sigml
allcsa.js:1222 07:00:44.400 Log: 07:00:44.400 Log: Set default SiGML URL to 'SignFiles/bad.sigml'.
:8000/favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this error
allcsa.js:1222 07:00:46.815 Log: 07:00:46.815 Avatar: SigningAvatar: Switch Avatar to marc
allcsa.js:1222 07:00:46.816 Log: 07:00:46.816 Status: Animgen by Client
allcsa.js:1222 07:00:46.816 Log: 07:00:46.816 CWASA : Initialisation ends
localhost/jas/loc2021/cwa/cwacfg.json:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this error
allcsa.js:1222 07:00:47.013 Log: 07:00:47.013 Avatar: SigningAvatar: Switch Avatar to marc
allcsa.js:1222 07:00:47.013 Log: 07:00:47.013 Status: Animgen by Client
allcsa.js:1222 07:00:47.013 Log: 07:00:47.013 CWASA : Initialisation ends
localhost/jas/loc2021/cwa/cwacfg.json:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this error
allcsa.js:180855 Uncaught TypeError: Cannot read properties of null (reading 'y')
    at Character.getAdjustViewY (allcsa.js:180855:29)
    at SigningAvatar.startNewCamera (allcsa.js:182176:23)
    at SigningAvatar.startNewCharacter (allcsa.js:182325:6)
    at bindForGL (allcsa.js:182283:13)
    at SigningAvatar.startBinaryAvatar (allcsa.js:182287:1)
    at SigningAvatar.loadNewAvatar (allcsa.js:182219:13)
    at allcsa.js:181862:13Understand this error
allcsa.js:1219 07:00:49.100 Warn: 07:00:49.100 Avatar: AvDataAccess: Error for http://localhost/jas/loc2021/avatars/COMMON.jar: [object ProgressEvent]
console.warn @ allcsa.js:1219Understand this warning
allcsa.js:1219 07:00:49.101 Warn: 07:00:49.101 Avatar: Cannot load COMMON config for GUI 0
console.warn @ allcsa.js:1219Understand this warning
localhost/jas/loc2021/avatars/COMMON.jar:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this error
localhost/jas/loc2021/cwa/h2s.xsl:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this error
allcsa.js:1219 07:00:49.117 Warn: 07:00:49.117 Avatar: AvDataAccess: Error for http://localhost/jas/loc2021/avatars/marc.jar: [object ProgressEvent]
console.warn @ allcsa.js:1219Understand this warning
allcsa.js:1219 07:00:49.117 Warn: 07:00:49.117 Avatar: SigningAvatar: Configuration files unavailable for 0: Avatar marc: [object ProgressEvent]
console.warn @ allcsa.js:1219Understand this warning
localhost/jas/loc2021/avatars/marc.jar:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by shoebham** [comment]
Closing as part of issue backlog cleanup. The Stanford parser jar is no longer tracked in the repo (removed via PR #23); install/download it locally as needed for development. Re-open or file a new issue if you hit a concrete error with steps to reproduce.
